#!/bin/sh
#
# ~/.xprofile
#

export QT_QPA_PLATFORMTHEME="qt5ct"

xrandr --output eDP1 --primary

# sh ~/.fehbg &

# if we have private ssh key(s), start ssh-agent and add the key(s)

id3=$HOME/.ssh/id_rsa
id4=$HOME/.ssh/id_github_rsa
if [ -x /usr/bin/ssh-agent ] && [ -f $id3 -o -f $id4 ];
then
    eval `ssh-agent -s`
    ssh-add $id3 $id4 < /dev/null
fi


# syndaemon -t -k -i 2 -d

# enable two finger scroll on touchpad for libinput
# xinput set-prop 14 289 0 1 0
# disable horizontal scrolling
# xinput set-prop 14 294 0
# disable disable while typing
# xinput set-prop 14 291 0

# export SOCKS_SERVER="127.0.0.1:12021"
# export SOCKS_VERSION=5

# export no_proxy="localhost,127.0.0.1,local.host,localhost.localdomain,192.168.0.105,inetcom.ru,google.com,google.ru,google.co.uk,.local,.docs,.dotcomltd.ru"

xset dpms 0 0 600
xset s off

$HOME/.pgenv/bin/pgenv start

# exec i3
