#!/bin/bash
# This hook is run after every virtualenv is activated.

# add virtualenv node modules to node path
_NODE_PATH="$NODE_PATH"
NODE_PATH="$VIRTUAL_ENV/node_modules:$NODE_PATH"

# add executable node modules to path
_PATH="$PATH"
PATH="$VIRTUAL_ENV/node_modules/.bin:$VIRTUAL_ENV/_project/node_modules/.bin:$VIRTUAL_ENV/_app/node_modules/.bin:$PATH"

# store path
_PWD="$PWD"

alias cdsrc='cd $VIRTUAL_ENV/src'
alias n='N_PREFIX=$VIRTUAL_ENV n'
