#!/bin/bash
# This hook is run after every virtualenv is deactivated.

# reset node path
NODE_PATH="$_NODE_PATH"
_NODE_PATH=

# reset path
PATH="$_PATH"
_PATH=

unalias cdsrc
unalias n

cd $_PWD

# reset pwd
_PWD=
